services:
  - type: worker
    name: domain-watcher
    env: node
    buildCommand: npm install
    startCommand: node domain-watcher.js
    plan: free
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ALERT_EMAIL
        sync: false
